### ISSUE TITLE
[Question] Initial user creation in Firezone

### ISSUE THREAD

**Issue by sdaberdaku** [Intuinewin/helm-charts#40]
Hello @Intuinewin, 

Thank you for the amazing work with the charts!

Could you please provide some more information on how to create the initial user with the Elixir interactive shell?

Thanks, 

Sebastian

**Comment by Intuinewin** [comment]
Hello,

I recommend you configure the mail adapter and don't provision any users yourself. Just use the classic registration flow.

But if you want to provision an account yourself you can read this README which explains how to access the elixir interactive shell and how to create accounts: https://github.com/firezone/firezone/blob/main/elixir/README.md

or use this file which is used to seed a test database https://github.com/firezone/firezone/blob/main/elixir/apps/domain/priv/repo/seeds.exs

**Comment by sdaberdaku** [comment]
Thanks for your prompt response!
Ideally I would like to avoid creating users altogether and attach my Identity Provider to Firezone. 
I will read the documentation you sent me, however if you have any suggestions on how to do that it would be very welcome. I am setting the OPENID_CONNECT_PROVIDERS env variable for google like so but the "google" login is not showing up on the login page.
```
global:
...
  # Common extra env for all pods
  extraEnv:
    - name: OPENID_CONNECT_PROVIDERS
      valueFrom:
        secretKeyRef:
          name: idp-credentials
          key: openid_connect_providers
```
with the secret looking sth like this:
```
[
  {
    "auto_create_users": true,
    "id": "google",
    "label": "google",
    "client_id": "zzzzz.apps.googleusercontent.com",
    "client_secret": "xxx",
    "discovery_document_uri": "https://accounts.google.com/.well-known/openid-configuration",
    "redirect_uri": "https://aaaaaaaaaaaa/auth/oidc/google/callback/",
    "response_type": "code",
    "scope": "openid email profile"
  }
]
```
